### ISSUE TITLE
Thrive Leads results in html code appearing in Prominent Keywords section

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#1134] opened 2017-04-20 14:41 UTC
## What did you expect to happen?
Prominent keywords would appear
## What happened instead?
HTML code appeared instead
## How can we reproduce this behavior?
**1.Installed Thrive Leads**

**2.Go to a post/page**

**3.Add a thrive leads shortcode**

![screen shot 2017-04-20 at 10 39 41 am](https://cloud.githubusercontent.com/assets/8238074/25236381/b3a99558-25b5-11e7-9de3-82083dfaad36.png)

**4.See html code**
![screen shot 2017-04-20 at 10 39 22 am](https://cloud.githubusercontent.com/assets/8238074/25236386/b7943f10-25b5-11e7-981c-9972d14e736e.png)

## Technical info

* Platform: WordPress 
* Platform version: 4.7.3
* Yoast SEO version: 4.6
* Thrive Leads: Version 1.95.15 ( https://thrivethemes.com/ )

**Comment by Pcosta88** [comment] 2017-04-20 14:41
Please inform the customer of conversation # 189501 when this conversation has been closed.

**Comment by CarolineGeven** [comment] 2017-04-21 06:47
Duplicate of #1044

**Closed by CarolineGeven** 2017-04-21 06:47 UTC
Labels: support
