### ISSUE TITLE
Readability Fails With Huge-IT Google Map Shortcodes

### ISSUE THREAD

**Issue by amboutwe** [Yoast/YoastSEO.js#976] opened 2016-12-09 17:53 UTC
### What did you expect to happen?
Readability to work

### What happened instead?
Errors in readabilty:
FeedbackAn error occurred in the ‘textSentenceLength’ assessment
FeedbackAn error occurred in the ‘textTransitionWords’ assessment
FeedbackAn error occurred in the ‘passiveVoice’ assessment
FeedbackAn error occurred in the ‘sentenceBeginnings’ assessment

Errors in console:
Error: unable to tokenize (repeats for each error above, example below)
![selection_106](https://cloud.githubusercontent.com/assets/8060612/21058856/3561cb5e-bdfd-11e6-88be-87b14547c650.png)

### How can we reproduce this behavior?

1. Install and activate [Huge-IT Google Map](https://wordpress.org/plugins/google-maps/) plugin.
2. Add a new post. Add the demo map.
3. Errors appear

Can you provide a link to a page which shows this issue?
Backend

### Technical info
* WordPress version: 4.7
* Yoast SEO version: 3.9
* Huge-IT Google Map version: 2.2.1

Reported to us here: https://wordpress.org/support/topic/errors-in-analysis-plugin-updated/
Reported to Huge-IT here: https://wordpress.org/support/topic/disables-yoast-seo-analysis/

**Comment by benvaassen** [comment] 2018-11-28 07:31
This should be fixed with 9.2 and is probably a duplicate of #840.

**Closed by benvaassen** 2018-11-28 07:31 UTC
Labels: compatibility, support
