### ISSUE TITLE
Snippet preview title and url match differently on focus keywords

### ISSUE THREAD

**Issue by diedexx** [Yoast/YoastSEO.js#141] opened 2015-11-09 12:40 UTC
The title and url in the snippet preview match in different ways.

The url matches when a word __contains__ the focus keyword
![edit_post_ _wpmu_subdirectory_trunk_dev_ _wordpress 2](https://cloud.githubusercontent.com/assets/5352634/11033581/95f00e8c-86e4-11e5-950e-8a464f1e67c8.png)
-
The title only matches if the word __is__ a complete word (and thus is surrounded by word boundaries).
(the meta description matches in the same way as the title does.)

![edit_post_ _wpmu_subdirectory_trunk_dev_ _wordpress](https://cloud.githubusercontent.com/assets/5352634/11033583/97bb33e0-86e4-11e5-9c9c-57c49060aefc.png)

-
<img width="411" alt="edit_post_ _wpmu_subdirectory_trunk_dev_ _wordpress 3" src="https://cloud.githubusercontent.com/assets/5352634/11033705/9d06e4c4-86e5-11e5-81f4-410929e62a10.png">

Using:
- WordPress 4.3.1 (multisite | subdirectory)
- Yoast SEO 3.0 (beta 9)

**Comment by CarolineGeven** [comment] 2015-11-10 08:51
Duplicate of #143

**Closed by CarolineGeven** 2015-11-10 08:51 UTC
