### ISSUE TITLE
Filter emojis from prominent words analysis

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1385] opened 2018-01-18 12:18 UTC
Emojis are currently treated as words in our prominent words analysis. They should be filtered based on their unicode values. For example, ✅  can be filtered by filtering the unicode value `\u2705`. This can help to avoid nonsensical results such as the one in the screenshot below.

![screen shot 2018-01-18 at 13 10 49](https://user-images.githubusercontent.com/27805437/35097705-85aea33c-fc51-11e7-9bbb-9bdf4e8f873d.png)

**Comment by Djennez** [comment] 2019-04-25 10:35
Duplicate of https://github.com/Yoast/wordpress-seo-premium/issues/1559

**Closed by Djennez** 2019-04-25 10:35 UTC
Labels: backlog, bug, component: prominent words
