### ISSUE TITLE
Readability analysis for the passive voice breaks when having "ling) is" in the editor 

### ISSUE THREAD

**Issue by benvaassen** [Yoast/YoastSEO.js#1270] opened 2017-10-25 11:20 UTC
## What did you expect to happen?
The passive voice not to break. 

## What happened instead?
The passive voice throws an error: FeedbackAn error occurred in the 'passiveVoice' assessment

## How can we reproduce this behavior?
- Create a new post
- Add the following text in the post: `ling) is`
- See the passive voice breaks and the following JavaScript error: `SyntaxError: Invalid regular expression: /(^|[ \u00a0 \n\r\t.,'()"+-;!?:/»«‹›<>])ling)($|[ \u00a0 \n\r\t.,'()"+-;!?:/»«‹›<>])/: Unmatched ')'`

![js_error](https://user-images.githubusercontent.com/11910661/31996031-2a92bbda-b987-11e7-8029-5f2e1be25aac.png)

## Technical info
* Platform: WordPress
* Platform version: 4.8.2
* Yoast SEO version: 5.7

**Comment by RolfKyburz** [comment] 2017-10-25 11:59
Thanks a lot, Ben! "ling)" is actually enough to make the passive voice assessment fail.
Best wishes,
-Rolf

**Comment by RolfKyburz** [comment] 2017-10-25 14:31
Hmmm ... "daring)" caused the same issue in another post — is the problem with "ing)"??? This starts to look like a fundamental flaw in the tokenizer, maybe affecting various other strings followed by a closing parenthesis?

**Comment by RolfKyburz** [comment] 2017-10-25 14:36
... more: I had a post with "crackling)" and "tuning)" — only avoiding the ")" after "ing" in **both** cases fixed the issue. I really looks like "ing)" is the culprit!

**Comment by manuelaugustin** [comment] 2017-10-31 09:00
I can reproduce the error when I'm downloading the latest version of the plugin, but not when I'm using the latest version of YoastSEO.js (1.22).

When using `ling( is` with an opening bracket, the error message is the same as the one in #1251, which has been fixed in YoastSEO.js 1.22. Is it possible that the latest version of the plugin is not using the latest release YoastSEO.js?

**Comment by manuelaugustin** [comment] 2017-11-01 09:53
This problem has been resolved in https://github.com/Yoast/YoastSEO.js/pull/1252 
The latest version of YoastSEO.js, which includes this bug fix, will be included in the next release of the plugin.

**Closed by manuelaugustin** 2017-11-01 09:53 UTC
Labels: queue ✨
