### ISSUE TITLE
Module for Readability Analysis: Skip lists for sentence beginnings ratings

### ISSUE THREAD

**Issue by SereniTeaTime** [Yoast/YoastSEO.js#2198] opened 2019-03-11 06:07 UTC
## What did you expect to happen?
In lists, I tend to start with the same word, which earns me a red bullet. I'd prefer it if the analysis would ignore lists.

More context:
I think it would be good to exclude lists from this test as lists often contain repetitive content by design, like further reading sources or when trying to make a point by repetition. Or it's even necessary to make things clearer. E.g. imagine a medical article that lists symptoms. The reader expects a structured way of presenting them, yes? ... it does this, it does that, it can lead to ... it can also lead to... you get my gist, I think. ;) 

## What happened instead?
I earned a red bullet for repeated sentence beginnings in lists. Since I aim to get an overall green bullet for readability, this drives me nuts.

## How can we reproduce this behavior?
Create a list where at least 3 bullets start with the same word.

## Technical info

* Platform: WordPress 
* Platform version: 5.1
* Yoast SEO version: 9.7 (free)

Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [ ] Gutenberg
- [ ] Classic Editor plugin

**Comment by Djennez** [comment] 2019-03-11 08:17
Closing this thread as a duplicate of https://github.com/Yoast/YoastSEO.js/issues/1190

**Closed as completed by Djennez** 2019-03-11 08:17 UTC
