### ISSUE TITLE
Multiple Focus Keyword Analysis Icon fails to be removed when Keyword is removed

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#1828] opened 2018-09-28 13:41 UTC
## What did you expect to happen?

When using multiple focus keywords the keyword analysis Icon would be removed when the keyword is removed.

## What happened instead?

It remained

## How can we reproduce this behavior?

**1.Add an extra focus keyword and save post/page**

<img width="939" alt="screen shot 2018-09-28 at 9 39 01 am" src="https://user-images.githubusercontent.com/8238074/46211756-59475c80-c302-11e8-85f3-d4b661c540ab.png">

**2. Click x to delete it**

<img width="978" alt="screen shot 2018-09-28 at 9 39 16 am" src="https://user-images.githubusercontent.com/8238074/46211784-65cbb500-c302-11e8-8651-1383b87fc567.png">

**3.Update Post**

**4.See the analysis icon remain**

<img width="962" alt="screen shot 2018-09-28 at 9 39 53 am" src="https://user-images.githubusercontent.com/8238074/46211822-7714c180-c302-11e8-8a1f-b365d4e3e336.png">

**5. Not sure if JS error is related?**

`Uncaught (in promise) TypeError: Cannot read property 'querySelectorAll'
`
## Technical info

* Platform: WordPress  
* Platform version: 4.9.8
* Yoast SEO version: 8.3

**Comment by Pcosta88** [comment] 2018-09-28 13:42
Please inform the customer of conversation # 429503 when this conversation has been closed.

**Comment by Djennez** [comment] 2020-09-07 11:59
Can't reproduce anymore, closing.

**Closed by Djennez** 2020-09-07 11:59 UTC
Labels: support
