### ISSUE TITLE
Module for Readability Analysis: Mark areas that will be skipped in sentence beginnings ratings

### ISSUE THREAD

**Issue by SereniTeaTime** [Yoast/YoastSEO.js#2199] opened 2019-03-11 06:10 UTC
## What did you expect to happen?
Sometimes we want repetitive beginning, e.g. to make a point.

Also, when quoting, I can not change the style and phrasing of the quote. I do not always use the "quote" tag for it but rather h tags. When several sentences in a quote start with the same word, it earns me a red bullet. 

I'd prefer if I could mark areas of the text where I deliberately accept this flaw and the analysis ignores the text.

## What happened instead?
I earned a red bullet for repeated sentence beginnings in quotes or other areas where I did this on purpose. Since I aim to get an overall green bullet for readability, this drives me nuts.

## How can we reproduce this behavior?
Create any text where at least 3 sentences start with the same word.

## Technical info
* Platform: WordPress 
* Platform version: 5.1
* Yoast SEO version: 9.7 (free)

Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [ ] Gutenberg
- [ ] Classic Editor plugin

**Comment by Djennez** [comment] 2019-03-11 08:31
Closing this thread as a duplicate of https://github.com/Yoast/wordpress-seo/issues/5231

**Closed as completed by Djennez** 2019-03-11 08:31 UTC
