### ISSUE TITLE
Competing links assessment marker doesn't mark anything.

### ISSUE THREAD

**Issue by Xyfi** [Yoast/YoastSEO.js#1350] opened 2017-12-22 14:25 UTC
## What did you expect to happen?
When I click the competing link assessment marker, I expect the link that links to the competing post to be marked.

## What happened instead?
Nothing gets marked.

## How can we reproduce this behavior?
* Create a post with a keyword and save it. Give it a unique and easy to remember title.
* Create a second post with the same keyword and create a link to the first post.
* Make sure the competing link assessment is shown. It has the following text in English: `You're linking to another page with the focus keyword you want this page to rank for. Consider changing that if you truly want this page to rank.`
* Click the marker and notice that the link is not highlighted as it should be.

## Technical info

* Platform: WordPress
* Platform version: 4.9.1
* Yoast SEO version: 6.0

**Comment by igorschoester** [comment] 2019-02-12 14:40
Closing this because it is a duplicate of https://github.com/Yoast/YoastSEO.js/issues/1155

**Closed by igorschoester** 2019-02-12 14:40 UTC
Labels: bug, component: highlighting, requires structured data / html parser
