### ISSUE TITLE
Media Attachment Pages fail to show correct word count and readability analysis

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#1959] opened 2018-11-05 19:58 UTC
## What did you expect to happen?

Attachment pages would have the editor area scanned for wordcount and readability. 

## What happened instead?

They were not

## How can we reproduce this behavior?
**1.Add words into editor area**
**2. See warnings**

_Readability_

<img width="1198" alt="screen shot 2018-11-05 at 2 49 48 pm" src="https://user-images.githubusercontent.com/8238074/48023216-21a2b000-e10b-11e8-877b-9d41906cfdb7.png">

_Word Count shows 0_

<img width="1016" alt="screen shot 2018-11-05 at 2 49 56 pm" src="https://user-images.githubusercontent.com/8238074/48023227-29faeb00-e10b-11e8-95c2-116f96a74290.png">

## Technical info

* Platform: WordPress 
* Platform version: 498
* Yoast SEO version: 903

**Comment by Pcosta88** [comment] 2018-11-05 19:58
Please inform the customer of conversation # 441168 when this conversation has been closed.

**Comment by benvaassen** [comment] 2018-11-07 13:42
Duplicate of https://github.com/Yoast/wordpress-seo/issues/6424

**Closed by benvaassen** 2018-11-07 13:42 UTC
Labels: support
