### ISSUE TITLE
Visual Composer Google Fonts URL Appear as the Prominent Words

### ISSUE THREAD

**Issue by iamazik** [Yoast/YoastSEO.js#1127] opened 2017-04-05 17:14 UTC
## What did you expect to happen?
The Visual Composer Google fonts URL wouldn't appear as the prominent words.

## What happened instead?
The Visual Composer Google fonts URL appears as the prominent words.

## How can we reproduce this behavior?

- Use the Visual Composer Custom Heading widget
- Select the font size and font family from the Google fonts library from the widget settings
- See the Prominent words section

## Example Content
```
[vc_column width="1/2" css=".vc_custom_1431699701193{margin-bottom: 0px !important;}"][vc_custom_heading text="This is custom heading" font_container="tag:h2|font_size:36|text_align:left|color:%23222533" google_fonts="font_family:Lato%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:300%20light%20regular%3A300%3Anormal" css=".vc_custom_1489608537878{margin-bottom: 10px !important;}"][vc_custom_heading text=" Intense Pulsed Light" font_container="tag:h3|font_size:26|text_align:left|color:%23a1b1bc" google_fonts="font_family:Lato%3A100%2C100italic%2C300%2C300italic%2Cregular%2Citalic%2C700%2C700italic%2C900%2C900italic|font_style:300%20light%20regular%3A300%3Anormal" css=".vc_custom_1489574599178{margin-bottom: 26px !important;}"][vc_column_text font_size="18" css=".vc_custom_1489611863679{margin-bottom: 28px !important;}"]Lorem Ipsum Dolor Is Sumit Lorem Ipsum Dolor Is Sumit Lorem Ipsum Dolor Is Sumit[/vc_column_text]
```

## Screenshot
![screen shot 2017-04-05 at 10 53 04 pm](https://cloud.githubusercontent.com/assets/8946603/24717790/76285752-1a55-11e7-9e6d-4db67de83a5f.png)

## Technical info

* Platform: WordPress
* Platform version: 4.7.3
* Yoast SEO version: 4.5
* Visual Composer version: 5.1.1

**Comment by iamazik** [comment] 2017-04-05 17:14
Please inform the customer of conversation # 188484 when this conversation has been closed.

**Comment by thulshof** [comment] 2017-04-06 06:46
Closing, duplicate of #1044

**Closed by thulshof** 2017-04-06 06:46 UTC
Labels: support
