### ISSUE TITLE
Parentheses at beginning of sentence are viewed as word in sentence beginning assessment

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#625] opened 2016-06-07 12:36 UTC
### What did you expect to happen?

Parenthesis not to be viewed as a word in the sentence beginning assessment.
### What happened instead?

In the sentence beginning assessment, repeated parentheses at the beginning of a sentence are viewed as a repeated words.
![schermafbeelding 2016-06-07 om 14 23 35](https://cloud.githubusercontent.com/assets/17744553/15857478/ed0f6de8-2cbb-11e6-983a-1b981c2a4011.png)
(There is also something wrong with the sentence detection, see #621)
### How can we reproduce this behavior?

Begin 3 consecutive sentences with parentheses and hit the mark button for sentence beginnings.
### Technical info
- Platform: WordPress 
- Platform version: 4.5.2
- Yoast SEO version: trunk

**Comment by atimmer** [comment] 2016-06-09 08:16
This should be mostly fixed by not splitting sentences on parentheses.

**Comment by Djennez** [comment] 2019-01-29 12:04
This issue is no longer relevant as it has either been fixed or removed (unable to reproduce). Closing this issue.

**Closed by Djennez** 2019-01-29 12:04 UTC
Labels: bug
