### ISSUE TITLE
Readability and content analysis errors with Arrow Twitter Feed plugin

### ISSUE THREAD

**Issue by priscillamc** [Yoast/YoastSEO.js#1840] opened 2018-10-05 21:36 UTC
## What did you expect to happen?
Added the Arrow Twitter Feed shortcode to a page and expected the readability and content analysis to work. 

## What happened instead?
Readability Analysis show errors in 'textSentenceLength', 'textTransitionWords', 'passiveVoice', and 'sentenceBeginnings'assessments. 

![screenshot_conflict_errors_1](https://user-images.githubusercontent.com/884156/46561033-e28efe00-c8c3-11e8-8c60-85aae35ab383.png)

In the browser console, there are the following errors: 'Error: unable to tokenize wp-seo-analysis-worker-830.min.js:13'

![screenshot_conflict_errors_2](https://user-images.githubusercontent.com/884156/46561126-38fc3c80-c8c4-11e8-80ff-12b795160216.png)

## How can we reproduce this behavior?

1. Install and activate [Arrow Twitter Feed](https://wordpress.org/plugins/arrow-twitter-feed/).
1. Go to Arrow Twitter Feed > Add New.
1. For 'Show Tweets From', add a twitter username or hashtag, then click Publish.
1. Copy the shortcode and insert into a page.
1. Add a focus keyword and check the Readability Analysis to see the errors.

## Technical info
* Arrow Twitter Feed v. 1.4.2
* Platform: WordPress
* Platform version: 4.9.8
* Yoast SEO version: 8.3 (free and premium)

**Comment by priscillamc** [comment] 2018-10-05 21:36
Please inform the customer of conversation # 431772  when this conversation has been closed.

**Comment by benvaassen** [comment] 2018-10-09 15:07
Probably fixed when this one is fixed: https://github.com/Yoast/YoastSEO.js/issues/840.

**Comment by moorscode** [comment] 2018-11-22 07:49
As #840 has been released in 9.2, this could be resolved - please check with the customer.

Other than that, we are not going to build in support for this specific plugin, so if there is no underlaying root cause we will not do anything with it.

**Closed by moorscode** 2018-11-22 07:49 UTC
Labels: backlog, bug, requires structured data / html parser, support
