### ISSUE TITLE
Eye Highlighting tool not working on "Paragraph ove 150 words long" warning with any styled text

### ISSUE THREAD

**Issue by rmarcano** [Yoast/YoastSEO.js#1352] opened 2017-12-26 18:06 UTC
## What did you expect to happen?
Eye highlighting tool to highlight long paragraphs that include links or styled text.

## What happened instead?
The tool did not highlight any text

## How can we reproduce this behavior?

1. Create a paragraph with more than 150 words do not include any links or colored text.
2. Highlight the paragraph with the warning using the Eye Highlighting tool.

![01](https://user-images.githubusercontent.com/1044883/34361972-47fd5ea0-ea3d-11e7-887f-3e518683297e.png)
3. Clear any highlighting and add a link to the paragraph or colored text.
4. Try to highlight the paragraph again. It should not highlight.
![02](https://user-images.githubusercontent.com/1044883/34361981-5c7daae2-ea3d-11e7-889a-b93821f665ee.png)

## Technical info
* Platform: WordPress 
* Platform version: 4.9.1
* Yoast SEO version: 6.0

**Comment by CarolineGeven** [comment] 2017-12-28 07:23
Duplicate of #1151

**Closed by CarolineGeven** 2017-12-28 07:23 UTC
Labels: support
