### ISSUE TITLE
Dotted Keywords doesn't works

### ISSUE THREAD

**Issue by charbonnier666** [Yoast/YoastSEO.js#2232] opened 2019-12-17 10:11 UTC
## What did you expect to happen?
Dotted keywords analysis works

## What happened instead?
Dotted Keywords analysis doesn't works

## How can we reproduce this behavior?
"St. Justice" example keyword

## Technical info

* Platform: WordPress
* Platform version: 5.3.1
* Yoast SEO version: 12.7.1

Which browser is affected (or browsers): 
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Other 

If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [ ] Gutenberg
- [ ] Classic Editor plugin

**Comment by Djennez** [comment] 2019-12-17 10:39
Closing as incomplete and duplicate of any of these: https://github.com/search?q=org%3Ayoast+period+keyphrase+is%3Aissue

**Closed as completed by Djennez** 2019-12-17 10:39 UTC
