### ISSUE TITLE
Update Readme with tests API and plugin init docs

### ISSUE THREAD

**Issue by omarreiss** [Yoast/YoastSEO.js#190] opened 2015-11-23 11:07 UTC
Including WP specific plugin info.

**Comment by stramel** [comment] 2015-12-08 19:58
Would love to have a nice example and better documentation on how to get going.

**Comment by amboutwe** [comment] 2016-02-03 18:12
From a premium user

>A simple solution which I'm trying to get to is to have a piece of JQuery that pulls off the html from an id or a class on a page and passes that to the SEO analysis. That would work for me, and I think it would work for the vast majority of other people, this would be simple to implement, and simple to understand.

**Comment by beatelite** [comment] 2017-01-03 17:21
Completely agree with all of this. We need better documentation to do a basic task like analyze a string from an id or class. I am very familiar with Js and can't even get basic analysis going. 

help!

**Comment by Djennez** [comment] 2019-03-05 08:28
Closing this as a duplicate of / in favor of https://github.com/Yoast/YoastSEO.js/issues/181 (that thread is older and has some additional info, even though it's probably outdated).

**Closed by Djennez** 2019-03-05 08:28 UTC
Labels: backlog, documentation
