### ISSUE TITLE
Passive sentence breakers not correctly identified

### ISSUE THREAD

**Issue by manuelaugustin** [Yoast/YoastSEO.js#1214] opened 2017-07-28 09:51 UTC
## What did you expect to happen?
Passive sentence breakers should be identified also when there’s a preceding word containing the same string of letters.

## What happened instead?
For example, the sentence fragment `who commented praise is due` is not passive, but according to the analysis, it is. When 'praise' is removed from the sentence, the analysis is correct.

**Comment by IreneStr** [comment] 2017-08-02 09:04
@manuelaugustin Isn't this a duplicate of #1210 and already closed by #1211?

**Closed** 2017-08-04 07:17 UTC
Labels: acceptance, bug, text analysis
