### ISSUE TITLE
Unable to tokenize in case of <blockquote class=

### ISSUE THREAD

**Issue by IreneStr** [Yoast/YoastSEO.js#796] opened 2016-07-13 12:30 UTC
When I was running the yoastseo-node module , I encountered the following error: 
### Error in console

```
Trace: { [Error: unable to tokenize]
  tokenizer2: { buffer: '<blockquote class="', line: 1, col: 1 } }
    at showTrace (/Users/Irene/Documents/yoastseo-node/node_modules/yoastseo/js/helpers/errors.js:17:11)
    at Assessor.executeAssessment (/Users/Irene/Documents/yoastseo-node/node_modules/yoastseo/js/assessor.js:174:3)
    at arrayMap (/Users/Irene/Documents/yoastseo-node/node_modules/lodash/_arrayMap.js:16:21)
    at map (/Users/Irene/Documents/yoastseo-node/node_modules/lodash/map.js:51:10)
    at Assessor.assess (/Users/Irene/Documents/yoastseo-node/node_modules/yoastseo/js/assessor.js:130:17)
    at Analyze (/Users/Irene/Documents/yoastseo-node/analyse.js:34:29)
    at Query._callback (/Users/Irene/Documents/yoastseo-node/analyse.js:82:9)
    at Query.Sequence.end (/Users/Irene/Documents/yoastseo-node/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Query._handleFinalResultPacket (/Users/Irene/Documents/yoastseo-node/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/Users/Irene/Documents/yoastseo-node/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)

```
## Input

```
   <div class="is-constrained">
            <h1 itemprop="headline">
                <span class="article__head__supertitle">Cristiano Ronaldo</span>
                <span class="article__head__title">Provokateur der Herzen</span>
            </h1>
            <div class="article__head__subtitle">
        <p>
            <strong>
                                    Über Cristiano Ronaldo hat sich während der EM eine kuriose Welle des Hasses entladen. Daran zeigt sich eine Fußballwelt, die an ihrer Männlichkeit und dem Spiel leidet.
                                                                     Von
                        <span itemprop="author" itemscope itemtype="http://schema.org/Person"><a href="http://www.zeit.de/autoren/H/David_Hugendick/index.xml" class="article__head__meta__author" itemprop="url"><span itemprop="name">David Hugendick</span></a></span>
                            </strong>
        </p>
    </div>
            <span class="article__head__meta-wrap">
                <span class="article__head__meta">
                    <time itemprop="datePublished" content="2016-07-11T17:14:36+02:00" datetime="2016-07-11T17:14:36+02:00" class="article__head__meta__date">
    11. Juli 2016, 17:14 Uhr
</time>                </span>
            </span>
        </div>
    </header>
</div>                                        <div class="article__body-wrap">
                <div class="article__body">
                                            <div class="article__page">
                                                <p class="is-constrained is-centered">
        Das Schönste an dem <a class="" href="http://www.zeit.de/sport/2016-07/portugal-frankreich-finale-fussball-em" target="_blank">Sieg der Portugiesen</a> waren die Bilder kurz vor dem Abpfiff: Cristiano Ronaldo, der unumstrittene Star der Mannschaft, sprang an der Seitenlinie herum, als wolle er nicht nur beide Mannschaften auf einmal coachen, sondern als spiele er alle Louis-de-Funès-Filme im Schnelldurchgang nach. Anderthalb Stunden zuvor, bevor er wie Lazarus auf die Bank zurückkehrte, wurde Ronaldo noch auf einer dieser baywatchfarbenen Bahren vom Rasen getragen, auf dem er unter Tränen zusammengebrochen war. Das Knie, das linke Bein, ein Franzose war ihm dagegen gelaufen, und alles an Ronaldo sagte in diesem Moment: Das war's. Ein Teil des französischen Publikums pfiff ihn aus, ihn, den weinenden, sich windenden Star, der nicht schluchzte, weil seine persönliche Seifenblase kaputt war, sondern weil er dem Team, seinem Team nicht mehr helfen konnte. Eine der traurigsten Szenen der EM wurde zugleich zu einer der hässlichsten.  <br>

    </p>
                    <p class="is-constrained is-centered">
        Es entlud sich ein kurios aufgestauter Hass auf den Mann, der während eines gesamten Turniers immer wieder zur Witzfigur heruntergeredet wurde. Weil er sich immer etwas zu sehr freute. Weil ihm noch immer kein Freistoßtor gelungen ist. Weil er, der Weltfußballer, doch nicht so weltbewegend spielte, wie es von ihm erwartet wurde, sich aber trotzdem bei jeder Gelegenheit in Pose warf. Plötzlich war Cristiano Ronaldo zu einem Bild geworden, an dem Medien die Verseifenoperung des Fußballs beklagten, die sie ja größtenteils, gemeinsam mit den Verbänden, selbst erzeugen. <br>

    </p>
  <p class="is-constrained is-centered">
        Eine Medienöffentlichkeit, der nach Abpfiff nichts Besseres einfällt, als
 ausgelaugte, keuchende Spieler danach zu fragen, wie sie sich nun nach 
der Niederlage fühlen und das dann für Relevanz und Drama halten. In der Fußball als Unterhaltungsshow inszeniert wird, mit Countdown vor dem Anstoß, als starte gleich eine Rakete, und der Zustand von Waden zu nationalen Angelegenheiten wird. Eine Welt, in der die Erwartungen an ein Turnier sofort als enttäuscht gelten, wenn müde Spieler müde dem Ball hinterherlaufen, weil sie eben müde sind. So müde wie Ronaldo anfangs, der ja für diesen Widerspruch zwischen Unterhaltungserwartung und Inszenierungsverdacht so wenig kann wie alle anderen Spieler. Aber an kaum einem Fußballer zeigt er sich so wie an ihm. <br>

    </p>
   <p class="is-constrained is-centered">
        Natürlich ist Ronaldo in seiner Welt ein Popstar, und den Popstarhabitus pflegt er wie kaum ein anderer Popstar es je täte. Er weiß nicht nur, wo das Tor, sondern auch, wo der Kameramann steht, der ihm das natürlich mit noch einer Nahaufnahme dankt.  Er weiß, wann er sich breitbeinig hinstellen und wann er die Oberlippe 
tragisch einklappen muss, wenn er einen Freistoß über die Latte 
primadonnert. Er weiß, dass er mit aufreizend geradem Rücken über den Platz läuft und er weiß auch, dass er immer etwas zu 
dramatisch guckt, als würde er gleich anfangen, <em>Starlight Express</em> zu 
singen. Und Ronaldo weiß auch, dass Fußball und Unterhaltung mittlerweile dasselbe sind und dass ihn viele deshalb für einen Schauspieler halten, obwohl er möglicherweise sogar mehr bei sich selbst ist als viele andere auf dem Platz.  <br>

    </p>
 <p class="is-constrained is-centered">
        Doch Figuren wie er sind in einem Sport verdächtig geworden, in dem von Publikum und Medien neben der Unterhaltung auch permanent die Authentizität eingefordert wird, die "echte Liebe" wie bei Borussia Dortmund und der ewige Kampf des Underdogs gegen das Großkapital der reichen Vereine beschworen wird, wozu etwa der Meistertitel von Leicester City in der Premier League hochgeorgelt wurde. Ronaldos expressiv zur Schau gestellte Emotionspalette steht für viele als Symptom für den Plastikfußball und die Kommerzialisierung, denen an anderen Stellen immer der Verweis auf Tradition, Kultur, Herkunft, Herz und das Gutewahreschöne entgegengehalten wird, als sei man kurz vor dem Eintritt in die AfD. <br>
    </p>
   <p class="is-constrained is-centered">
        Dass Ronaldo nicht nur als Sinnbild für den Fußballkommerz steht, sondern sich auch noch selbst zur Ware macht, die er CR7 nennt, wirkt da wie eine Provokation. CR7, das klingt zunächst eher wie C3PO, wie ein Roboter, eine Maschine. Schlimmstenfalls wie eine seelenlose Kunstfigur, <a class="" href="http://www.zeit.de/sport/2016-07/fussball-em-bilanz-hype" target="_blank">ein Verrat an den Idealen eines Sports</a>, von denen eigentlich kaum noch jemand weiß, welche das sein sollen. Dabei kann uns Ronaldo möglicherweise helfen, sie wiederzufinden.

    </p>
<h2 class="article__subheading is-constrained is-centered">
        Superheldenkind im Körper eines Hochleistungssportlers
    </h2>
     <p class="is-constrained is-centered">
         Er hat sich nämlich das Kindliche bewahrt, aus dem aller Drang entspringt, überhaupt gegen einen Ball zu treten. Und zum Kindlichen gehören eben die Emotionen, die nur in ihrem Superlativ vorhanden sind: Wut, wenn etwas misslingt. Freude, wenn man gewinnt. Trauer, wenn man verliert. Er macht das nicht für die Kamera, er ist das. Und jedes Spiel mit Ronaldobeteiligung bietet eben die Möglichkeit, in dieser zugleich durchinszenierten und durchrationalisierten Fußballwelt, in der jeder gelaufene Kilometer notiert und der Rasen wie ein Großraumbüro aufgeteilt wird, noch einmal das Drama des hochbegabten Kindes zu sehen, das sich selbst einen Superheldennamen gegeben hat. Das aufstampft, wenn ein Gegentor fällt. Das so überdreht jubelt, wenn es gewonnen hat. Ein Superheldenkind im Körper eines Hochleistungssportlers, das sich vor einem Freistoß hinstellt wie Django mit Monatskarte im Schulbus. Lionel Messi wirkt in seiner nahezu ferngesteuerten Playstationperfektion jedenfalls roboterhafter als er. <br>

    </p>
                    <p class="is-constrained is-centered">
        Ronaldos ungezügelte Gefühle kann man natürlich mutwillig mit Theatralik oder Gekünstel verwechseln, wenn man ihm etwas Böses will, und offenbar wollten das während der EM viele. Man musste nur in die Social-Media-Kanäle schauen, um die Häme zu sehen, die über Ronaldo während der gesamten EM ausgegossen wurde. Sie reichte von "Heulsuse" über witzig gemeinte Bewegtbildchen bis zum Wort "Tucke" und dem Hinweis aufs "Feminine", und man möchte in die Geistesabgründe, aus denen so etwas hervorgerülpst wird, nicht weiter hinabsteigen. Selbst öffentlich-rechtliche Kommentatoren juxten, CR7 habe wohl seine "Pumps" nicht dabei und fügten jedem positiven Satz über ihn noch die Formulierung hinzu: "Was auch immer man sonst über ihn meinen kann." <br>

    </p>
                    <blockquote class="
                    quote
            ">
        <span class="quote__text">Ibrahimovic ist genau auf die Art arrogant, wie es offenbar viele selbst gern wären, wenn sie nur könnten, was er kann.</span>
            </blockquote>
                    <p class="is-constrained is-centered">
        Es ist schwer zu sagen, warum Cristiano Ronaldo so viele Zuschauer in 
ihrer Männlichkeit beleidigt oder in dem, was sie dafür halten. Warum Menschen, die sich bei sämtlichen anderen Themen der Welt vielleicht uneins wären, sich ausgerechnet bei Ronaldo in ihrer Abneigung vereinen. Vielleicht wegen der präzise gegelten Haare, des unrealistisch trainierten Oberkörpers, der Glitzerohrringe, des Ehrgeizes, des Pathos oder allem zusammen. Und man kann das alles als Extravaganz verspotten, zumal in Deutschland, einem 
Fußballland, in dem das hansikrausfilmhafte Gezwinker von Thomas 
Müller als genau die Art von "Eckigkeit" gilt, die man zu bewundern bereit ist. Dass die Firma "La Mannschaft" genauso wenig stört wie das Lufthansa-Senatorlounge-Deutschland, zu dem diese Firma gehört. Die oft formulierte Sehnsucht nach "echten Typen" jedenfalls erfüllte während der EM seltsamerweise weniger Ronaldo als Zlatan Ibrahimović, der ja inzwischen so etwas wie der Lemmy Kilmister des Strafraums zu sein scheint, und dessen actionfigurhafte Großkotzigkeit irgendwie als cool gilt. Weil Ibrahimović genau auf die Art arrogant ist, wie es offenbar viele selbst gern wären, wenn sie nur könnten, was er kann. <br>

    </p>
                    <p class="is-constrained is-centered">
        Zum Unterschied von Ibrahimović und Ronaldo wurde öfter erwähnt, dass Ibrahimović immerhin selbstironisch über sich rede. Und wahrscheinlich stimmt es, dass es Ronaldo, wie einem Kind, an Selbstironie fehlt, was 
andererseits in Zeiten, da selbst Friseursalons ironische Namen tragen, auch zu 
vernachlässigen ist. Und die Suche nach dem Wahren und Echten im ansonsten falschen Fußball gipfelte schließlich in der sonderbaren Verhaustierung der Isländer, die Wikinger mit den putzigen Nachnamen von der fernen, noch vermeintlich von allem Fußballkommerz unbehelligten Insel. Wo man die Echtheit vermutete, die man in der Oberflächen- und Oberkörperwelt vermisst hat, für die Cristiano Ronaldo angeblich steht. <br>

    </p>
                    <p class="is-constrained is-centered">
        Dabei verkörpert Ronaldo genau das, was man vom Fußball nur wollen kann: Affekt, Tragik, Kitsch, Spiel, das Kindliche und das Unberechenbare. Falls er das alles nur spielt, ist er wirklich ein sehr guter Schauspieler und verdient allein deswegen unsere Bewunderung. Wenn nicht, sollte man langsam anfangen, ihm zu glauben, als er mit dem Europameisterpokal dasteht, sich ihn auf den glänzend frisierten Europameisterkopf setzt wie ein Clown. Und noch während der Kommentator spöttisch fragt, wer so etwas denn sehen will, sollte man antworten: Wir alle.<br>

    </p>

                        </div>



                                                        </div>

```

**Comment by atimmer** [comment] 2016-07-13 12:56
This is probably just because 
```
 <blockquote class="
                    quote
            ">
```
is invalid HTML, we should still look into preventing us from erroring out. Is there a way to discard the invalid HTML?

**Comment by benvaassen** [comment] 2018-11-28 07:33
I can no longer reproduce this, probably fixed with https://github.com/Yoast/YoastSEO.js/issues/840. Closing this one.

**Closed by benvaassen** 2018-11-28 07:33 UTC
Labels: bug
