### ISSUE TITLE
Flesch reading ease; how to improve?

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/YoastSEO.js#133] opened 2015-11-04 12:56 UTC
**Problem description**
Different scores on the Flesch Reading Ease test give different feedback in the content analysis, explaining that you're on the rigth track, or that you should improve something.

However, if the reading ease of your text is mediocre, there's no suggestion as to how to improve your text. 

**Example**
`The copy scores 61.1 in the Flesch Reading Ease test, which is considered ok to read.`
![edit_post_ _wpbeta_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/10938577/b177c29a-82fb-11e5-8ee1-d5ded8c17d8d.png)

**Possible solutions**
- Add call-to-action or feedback on how to further improve the reading ease.
- Change the bullet to green

**Tested versions**
WordPress 4.4-beta-2
Yoast SEO 3.0-beta-4

**Comment by benvaassen** [comment] 2018-06-27 06:59
When you score 60+ on the test, it's now a good result: 
![good_result](https://user-images.githubusercontent.com/11910661/41957655-f103a4e8-79e7-11e8-942a-ff6d11e54dd9.png)

Between 50 and 60 shows as an improvement with a suggestion on how you can improve the test score: 
![improvement](https://user-images.githubusercontent.com/11910661/41957676-0080ab1e-79e8-11e8-84b8-9f31e0ca936a.png)

Therefore, I believe the issue is no longer relevant and I'm closing it.

**Closed by benvaassen** 2018-06-27 06:59 UTC
Labels: enhancement, text analysis
