### ISSUE TITLE
Passive voice assessment breaks on link

### ISSUE THREAD

**Issue by rensw90** [Yoast/YoastSEO.js#913] opened 2016-10-03 10:33 UTC
For the blogpost about installing the onboarding wizard the passive voice did not mark the text correctly
## What did you expect to happen?

The markers to mark the entire sentence.
## What happened instead?

The sentence was marked until a link
## How can we reproduce this behavior?

This sentence was used:
![edit_dev_article_ _yoast_ _wordpress](https://cloud.githubusercontent.com/assets/7293908/19034724/68039082-8965-11e6-9c7c-54d75e4199bb.jpg)
## Technical info
- Platform: WordPress
- Platform version: 4.6
- Yoast SEO version: latest trunk from 3 oktober

**Comment by terw-dan** [comment] 2017-02-07 15:29
As I cannot reproduce this issue anymore, and marking the links works fine, I'm closing this.

**Closed by terw-dan** 2017-02-07 15:29 UTC
Labels: bug
