### ISSUE TITLE
Snippet editor shows wrong URL on Front Page

### ISSUE THREAD

**Issue by monbauza** [Yoast/YoastSEO.js#192] opened 2015-11-24 07:58 UTC
It always displays domain/example-post/ whereas it should read just the domain

![image](https://cloud.githubusercontent.com/assets/9658774/11360939/5c9dec7a-9289-11e5-88bf-5727d0c7316a.png)

**Comment by monbauza** [comment] 2015-12-11 07:38
Please inform the customer of conversation # 89617 when this issue has been closed.

**Comment by monbauza** [comment] 2015-12-11 12:38
Please inform the customer of conversation # 89183 when this issue has been closed.

**Comment by AskKim** [comment] 2016-01-13 03:25
Although this is probably a YoastSEO.js issue, this ticket may be a duplicate of this other one: https://github.com/Yoast/wordpress-seo/issues/3370

**Comment by atimmer** [comment] 2016-03-25 20:34
This has been fixed in Yoast SEO 3.1, which corresponds to YoastSEO.js 1.1.

**Closed by atimmer** 2016-03-25 20:34 UTC
Labels: bug, wordpress specific
