### ISSUE TITLE
[Enhancement] Do not Count the Bullet point or dot or other special characters as part of the Consecutive Sentences Warning

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/YoastSEO.js#2177] opened 2019-02-27 16:23 UTC
## What did you expect to happen?

The bullet character would not be counted as part of the consecutive sentences warning

## What happened instead?

It Was

## How can we reproduce this behavior?

**1. Create sentences on new lines**

**2. On each new line preface it with a bullet**

**3. See Yoast pick-up the bullet point and count it as a consecutive sentence**

<img width="1209" alt="screen_shot_2019-02-27_at_11_19_32_am" src="https://user-images.githubusercontent.com/8238074/53505556-0d037280-3a82-11e9-8507-ffe74625987f.png">

**NOTES:**
The highlight tool is expected to highlight the bullet points

## Technical info

* Platform: WordPress
* Platform version: 5.1, Gutenberg
* Yoast SEO version: 9.7

**Comment by Djennez** [comment] 2019-03-01 07:54
The analysis is correct, but the question is: do we want to count symbols and non-alphanumeric words and characters towards the consecutive sentence score? @manuelaugustin ?

Besides that question I think that this use-case is kind of an edge case. How often do bullets get freehanded instead of lists? It isn't practical and not very SEO friendly.

**Comment by Pcosta88** [comment] 2020-02-28 15:07
Please inform the customer of conversation # 589308 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2020-06-18 17:14
Please inform the customer of conversation #622792 when this conversation has been closed.

**Comment by mmikhan** [comment] 2020-07-22 18:42
@Djennez isn't it a duplicate of https://github.com/Yoast/YoastSEO.js/issues/1190?

**Comment by fabien-corail** [comment] 2020-07-31 17:09
Has this been fixed ?

**Comment by rumejan** [comment] 2020-08-31 06:09
Please inform the customer of conversation #643303 when this conversation has been closed.

**Comment by rumejan** [comment] 2020-09-18 02:18
Please inform the customer of conversation #650710 when this conversation has been closed.

**Comment by monbauza** [comment] 2020-10-05 10:54
Please inform the customer of conversation # 650767 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2020-11-19 14:59
Please inform the customer of conversation # 667603 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2020-11-19 16:30
Please inform the customer of conversation # 667829 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2020-11-20 18:25
Please inform the customer of conversation # 667179 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2020-11-23 19:08
related https://github.com/Yoast/featurerequests/issues/719

**Comment by michaelbriantina** [comment] 2020-12-11 05:42
Please inform the customer of conversation # 677801 when this conversation has been closed.

**Comment by michaelbriantina** [comment] 2021-03-03 08:54
Please inform the customer of conversation # 699934 when this conversation has been closed.

**Comment by josh-yoast** [comment] 2021-03-16 13:57
Please inform the customer of conversation # 710783 when this conversation has been closed.

**Comment by michaelbriantina** [comment] 2021-07-22 02:56
Please inform the customer of conversation # 765412 when this conversation has been closed.

**Comment by Djennez** [comment] 2021-08-06 12:10
Closing this. For real lists, refer to this issue: https://github.com/Yoast/wordpress-seo/issues/17326 . For manually adding symbols at the start of a sentence... Well, it is theoretically still consecutive sentences starting with the same character / word.

**Closed as completed by Djennez** 2021-08-06 12:10 UTC
Labels: enhancement, support, needs-decision
