### ISSUE TITLE
Snippet editor shows wrong URL on product pages

### ISSUE THREAD

**Issue by monbauza** [Yoast/YoastSEO.js#200] opened 2015-12-03 10:11 UTC
Yoast SEO 3.0.6
WooCommerce 2.4.10
Twenty Fifteen theme
WordPress 4.3.1

![image](https://cloud.githubusercontent.com/assets/9658774/11557703/5c98f572-99ae-11e5-80e5-5290d27eb669.png)

**Comment by monbauza** [comment] 2015-12-11 12:38
Please inform the customer of conversation # 89183 when this issue has been closed.

**Comment by donadenise** [comment] 2015-12-12 22:40
any news on this - still waiting!!

**Comment by AskKim** [comment] 2015-12-13 21:40
Please inform the customer of conversation # 89570 when this issue has been closed.

**Comment by stramel** [comment] 2015-12-22 11:52
:+1: I am getting this issue too.

Permalink setting: [x] Custom  `/%category%/%postname%/`

YoastSEO is showing like it is `/%postname%/`

**Comment by Rarst** [comment] 2015-12-22 13:45
Is this this repo issue or plugin's? Not sure what's the split is between them on snippet and stuff.

Related https://github.com/Yoast/wordpress-seo/issues/3514

**Comment by stramel** [comment] 2015-12-22 15:42
Looks like to me that it is an issue with the wordpress-seo plugin

**Comment by atimmer** [comment] 2016-01-18 15:27
This is an issue with both. YoastSEO.js should support arbitrary URL structures in a standardised format and Yoast SEO for WordPress should pass the WordPress structure to YoastSEO.js in this standardised format.

**Comment by monbauza** [comment] 2016-03-02 08:29
This still happens in Yoast SEO 3.1

**Comment by monbauza** [comment] 2016-03-02 08:30
Please inform the customer of conversation # 103839 when this issue has been closed.

**Comment by badhoc** [comment] 2016-04-14 09:51
Anyone know of an easy fix for this yet?

**Comment by distille** [comment] 2016-05-25 08:30
Similar issue here. Created CPT (no archive, using Custom post types UI -plugin).
Wordpress permalink: sitename.dev/my-cpt/new-cpt-page
Yoast snippet preview URL: sitename.dev/new-cpt-page
I´m using: Yoast 3.2.5, Custom Post Type UI 1.3.4, WordPress: 4.5.2 Twenty sixteen

**Comment by damienmcd** [comment] 2016-06-03 11:03
I'm having the same issue.
I set the CPT up manually in functions.php

Permalink: mysite.com/whats-on/event-title
Yoast snippet: as mysite.com/event-title

Has there been any update on this yet?

Using: Yoast 3.2.5, WordPress 4.5.2 with custom theme.

**Comment by cmartini** [comment] 2016-06-24 17:40
Using 3.3.2 and having the same issue...

**Comment by cedricpereira** [comment] 2016-08-01 22:11
**Hi, any news about this problem?** 
Thanks!

_Using Yoast SEO 3.4 and WP 4.5.3._

**Comment by customer300** [comment] 2016-08-09 20:56
I'm using Yoast 3.4.2 and Wordpress 4.5.3 and I have the same problem. The Snippet editor doesn't show the real complete URL on pages. For example, it shortens all the URL:  www.mysite/1/2/3/4.html   to  www.mysite/1.html
Bad support by Yoast here!! :) Thinking about changing plugin.

**Comment by codemonkeynorth** [comment] 2016-08-17 00:58
Hi,

I have the same issue as @monbauza . Yoast strips /product/  from my  Custom Post Type (created with CPT UI)

I wonder if it is just an issue with the google preview script though, as opposed to actually affecting the site?

thanks
J

**Comment by cedricpereira** [comment] 2016-08-17 09:06
@codemonkeynorth, absolutely. It is only a bug with the preview snippet (the google preview). The source code is correct if your CPT is well set up. Don't change anything in your page (ID, slug, etc.), we only have to wait a new version which will correct it.
Have a good day!

Cédric

**Comment by UyenTon** [comment] 2017-01-04 11:03
I'm currently using WP 4.6.1 and Yoast SEO plugin 4.0, I have the same issue with snippet URL (mydomain.com/category/page-name => snippet: mydomain.com/page-name/). Anyone has idea to fix this?

**Comment by cedricpereira** [comment] 2017-01-04 12:44
Hi UyenTon,
It's only a bug with snippet, but as I said 5 months ago, if your CPT or in your case category is well set up, your URL will be optimized for search engines and will keep all informations in it. Don't know when the Yoast team planned to fix it because it's really disturbing! 
For the moment, be reassured, it is simply a display bug with Yoast snippet. 
Have a nice day!

**Comment by UyenTon** [comment] 2017-01-05 03:00
@cedricpereira Oh, I see. Thanks for your quick response. Have a nice day!

**Comment by bmihajlovski** [comment] 2017-03-02 18:02
I am experiencing not only a snippet display problem but search engine results errors too. for example, although my default urls are domain.com/product/product-name and domain.com/category/subcategory yoast changes them to domain/product-name and domain/subcategory on google, and when clicked on google you get invalid (404 page) destination, because the link that is displayed on google is not existing.
Please help me.

**Comment by cedricpereira** [comment] 2017-03-02 19:15
@bmihajlovski Could you please post your CPT source code? Thanks.

**Comment by CarolineGeven** [comment] 2018-09-25 09:54
Duplicate of https://github.com/Yoast/wordpress-seo/issues/3514

This issue will be addressed soon.

**Closed by CarolineGeven** 2018-09-25 09:54 UTC
Labels: bug, snippet editor

**Comment by vetlaser** [comment] 2019-04-15 17:50
After I created subcategory for post in admin area, YOAST snippet permalink shown doesn't include parent category snug, only subcategory snug,   is this resolved?  right now for each category page, I have two different permalink that both works, but I need to eliminate #1:
1) /MySubCategory
2) /MyCategory/MySubCategory
