### ISSUE TITLE
subheading followed by more than 300 words : count error

### ISSUE THREAD

**Issue by cseguenot** [Yoast/YoastSEO.js#2204] opened 2019-03-12 16:07 UTC
## What did you expect to happen?
the alert "1 subheading is followed by more than the recommended maximum of 300 words" should be displayed only if the subheading is realy followed by more than 300 words

## What happened instead?
Il the subheading is followed by a bulleted list with numbers, the alert is displayed even if there is less than 300 words after the subheading (only 124 words in my case).
It seems that each digit is considered as a word.

## How can we reproduce this behavior?
Write a bulleted list withe numbers after the subheading. Here is my example (it is an index of a video) 
0:00 : plan de la présentation
1:20 : La mise en page de la feuille Excel
3:23 : 1ère méthode : enregistrer le classeur Excel en PDF. Les propriétés et la qualité du doc PDF
4:45 : options (sélection du contenu, norme PDF/A)
7:28 : enregistrement en PDF selon 2 qualités différentes et comparaison des tailles de fichiers
10:00 : 2de méthode : imprimante PDF
10:57 : propriétés de Foxit PDF Printer
12:05 : création d'un profil pour la compression des image et l'inclusion des polices dans le fichier
14:30 : génération des fichiers PDF pour chaque feuille et comparaison de la taille de fichier avec la méthode précédente
15:55 : rassemblement des fichiers en un seul
17:24 : synthèse 

## Technical info

* Platform: WordPress
* Platform version: 5.1
* Yoast SEO version: 10.0

Which browser is affected (or browsers): 
- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Other 

If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [x] Gutenberg
- [ ] Classic Editor plugin

**Comment by Djennez** [comment] 2019-03-13 08:20
Hi @cseguenot , I am unable to replicate your issue:

![Add_New_Post_‹_WordPress_5_1_—_WordPress](https://user-images.githubusercontent.com/34372510/54263302-ce38e680-4570-11e9-9af7-4d3846f44a1a.png)

Are you running another language? Or is anything different set up compared to my screenshot above?

**Comment by cseguenot** [comment] 2019-03-13 08:54
Hi Djennez,
I'm indeed in french. Nothing else different...

**Comment by Djennez** [comment] 2019-03-13 11:18
In French I am also unable to reproduce this issue with the default settings. Are you sure you're not referring to the analysis of your total text being too short (shorter than 300 words)?

Please test if this is caused by other plugins or themes by disabling all but the Yoast plugin and switching the theme to the twentynineteem theme. If this solves the issue, try re-enabling the plgins one by one to see if one of them causes the issue to appear.

**Comment by cseguenot** [comment] 2019-03-13 17:26
Yes, my post has more than 1300 words.
To my great surprise, the bug is no longer present today although I did not change anything in my post. 
It seems that restarting my PC solved the problem.
So you can close the bug, because I can not reproduce it either...
Thank you for your time
Sincerely

**Comment by Djennez** [comment] 2019-03-14 07:16
Allright, thanks for letting me know! It might have been something to do with cache then. Closing this thread.

**Closed as completed by Djennez** 2019-03-14 07:16 UTC
Labels: wait for feedback
