### ISSUE TITLE
Same 2 errors in 'Analysis Results' for every post.

### ISSUE THREAD

**Issue by creativehelm** [Yoast/YoastSEO.js#1744] opened 2018-08-29 00:21 UTC
## What did you expect to happen?
Working (error free) 'keywordDensity' assessment and 'largestKeywordDistance' assessment
## What happened instead?
[Error] Unhandled promise rejection – Error: unable to tokenize — wp-seo-analysis-worker-810.min.js:12

See below:

<img width="604" alt="screen shot 2018-08-28 at 2 44 58 pm" src="https://user-images.githubusercontent.com/1379985/44757653-fd13d180-aae4-11e8-8bae-16346e8f8c10.png">

## How can we reproduce this behavior?

Create a post with the visual editor disabled—make sure to include links and images with HTML, and make the post at least 1,500 characters in length (in English). 

Make sure to set the 'Focus keyword'.

Perhaps add a recipe with appropriate markup...

## Technical info

* Platform: **WordPress**
* Platform version: **4.9.8**
* Yoast SEO version: **Yoast SEO Premium 8.1**

**Comment by benvaassen** [comment] 2018-11-28 07:30
This should be fixed with 9.2 and is a duplicate of #840.

**Closed by benvaassen** 2018-11-28 07:30 UTC
