### ISSUE TITLE
Focus keyword does not get counted in table

### ISSUE THREAD

**Issue by CarolineGeven** [Yoast/YoastSEO.js#356] opened 2016-03-21 12:30 UTC
When there are tables in the post and the keyword is in that post, the keyword density does not get counted.

For example, with the example below, the keyword 'keyword table' is only found once, but this should be three times.
![schermafbeelding 2016-03-21 om 13 33 15](https://cloud.githubusercontent.com/assets/8614579/13918651/0192a63a-ef69-11e5-9d94-a212a60785e1.png)

**Comment by CarolineGeven** [comment] 2016-03-21 12:31
Please inform the customer of conversation # 107973 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2016-03-28 14:47
Please inform the customer of conversation `#110137` when this conversation has been closed.

**Comment by Djennez** [comment] 2019-03-05 09:41
I am unable to reproduce this issue, closing this thread.

**Closed by Djennez** 2019-03-05 09:41 UTC
Labels: bug, support, text analysis
